services:
  agent-chatbot-app: 
    build: .
    ports:
      - 8000:8000
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
    networks:
      - agent-chatbot-app-network
# volumes:
#   data:
#     driver: local

networks:
  agent-chatbot-app-network:
    driver: bridge
